language: cpp

matrix:
  include:
  - os: linux
    compiler: gcc
    env: compiler=g++-4.8
    addons:
      apt:
        sources: ['ubuntu-toolchain-r-test']
        packages: ['g++-4.8']

  - os: linux
    compiler: gcc
    env:
    - COMPILER=g++-8
    - CXXFLAGS=-std=c++17
    addons:
      apt:
        sources: ['ubuntu-toolchain-r-test']
        packages: ['g++-8']

script:
# make sure CXX is correctly set
- if [[ "${COMPILER}" != "" ]]; then export CXX=${COMPILER}; fi

# show OS/compiler version
- uname -a
- $CXX --version

# build
make -j4 release

# run test
./build/robin-hood-test